baseURL = "https://iton.github.io/"
title = "Ihsan Tonuzi"
theme = "hugo-coder"
languageCode = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
author = "Ihsan Tonuzi"
license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Ihsan Tonuzi's personal website"
keywords = "blog,developer,personal"
dateFormat = "January 2, 2006"
since = 2025
colorScheme = "auto"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/iton0/"

[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/iton0/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 3
url = "https://www.linkedin.com/in/itonuzi/"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"
